name: BryonBlack
favicon: null
layout_spectrum: 0.26601
typography_spectrum: 0.25194
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#51cddf'
    - '#ffffff'
    - '#bfbfbf'
    - '#357c88'
  brandStrength: 0.6875
  lightness: 0.4066871979739517
  saturation: 0.41715332004241645
  rhythmicContrast: 0.5
purpose: []
