typography_spectrum: 0.25194
color:
  brandColors:
    - '#0d0d0d'
    - '#51cddf'
    - '#ffffff'
    - '#bfbfbf'
    - '#357c88'
  brandStrength: 0.9375
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26601
analytics:
  google: null
  facebook: null
  twitter: null
name: BryonBlack
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Bryon Black
description: Portrait Photographer
purpose: []
