name: BryonBlack
favicon: null
layout_spectrum: 0.6550033779349178
typography_spectrum: 0.8418868225999177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.731037134071812
  lightness: 0.4066871979739517
  saturation: 0.41715332004241645
  rhythmicContrast: 0.599874169100076
purpose: []
