name: BryonBlack
favicon: null
layout_spectrum: 0.26601
typography_spectrum: 0.25194
title: 'Weddings + Portraits | Worldwide Awesome'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#51cddf'
    - '#ffffff'
    - '#bfbfbf'
    - '#357c88'
  brandStrength: 0.9375
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
